// Generated by tools/gen_stubs.py -- do not edit; add real
// implementations elsewhere in platform/ (these stubs are weak).
#include "port_compat.h"
#include "port_stub.h"
#include <dolphin/ai.h>
#include <dolphin/ar.h>
#include <dolphin/arq.h>
#include <dolphin/base/PPCArch.h>
#include <dolphin/card.h>
#include <dolphin/card/CARDCheck.h>
#include <dolphin/card/CARDCreate.h>
#include <dolphin/card/CARDFormat.h>
#include <dolphin/card/CARDMount.h>
#include <dolphin/card/CARDOpen.h>
#include <dolphin/card/CARDRead.h>
#include <dolphin/card/CARDStat.h>
#include <dolphin/card/CARDWrite.h>
#include <dolphin/db/DBInterface.h>
#include <dolphin/dsp.h>
#include <dolphin/dvd.h>
#include <dolphin/gd/GDBase.h>
#include <dolphin/gd/GDGeometry.h>
#include <dolphin/gd/GDLight.h>
#include <dolphin/gd/GDPixel.h>
#include <dolphin/gd/GDTev.h>
#include <dolphin/gd/GDTransform.h>
#include <dolphin/gx.h>
#include <dolphin/gx/GXBump.h>
#include <dolphin/gx/GXCpu2Efb.h>
#include <dolphin/gx/GXCull.h>
#include <dolphin/gx/GXDispList.h>
#include <dolphin/gx/GXDraw.h>
#include <dolphin/gx/GXFifo.h>
#include <dolphin/gx/GXFrameBuffer.h>
#include <dolphin/gx/GXGeometry.h>
#include <dolphin/gx/GXGet.h>
#include <dolphin/gx/GXLighting.h>
#include <dolphin/gx/GXManage.h>
#include <dolphin/gx/GXPerf.h>
#include <dolphin/gx/GXPixel.h>
#include <dolphin/gx/GXTev.h>
#include <dolphin/gx/GXTexture.h>
#include <dolphin/gx/GXTransform.h>
#include <dolphin/mtx.h>
#include <dolphin/os.h>
#include <dolphin/os/OSAlloc.h>
#include <dolphin/os/OSCache.h>
#include <dolphin/os/OSContext.h>
#include <dolphin/os/OSError.h>
#include <dolphin/os/OSFont.h>
#include <dolphin/os/OSMemory.h>
#include <dolphin/os/OSMessage.h>
#include <dolphin/os/OSMutex.h>
#include <dolphin/os/OSReset.h>
#include <dolphin/os/OSResetSW.h>
#include <dolphin/os/OSRtc.h>
#include <dolphin/os/OSStopwatch.h>
#include <dolphin/os/OSThread.h>
#include <dolphin/pad.h>
#include <dolphin/thp.h>
#include <dolphin/vi/vifuncs.h>

template <class T> static inline T stub_default() { T t = T(); return t; }

SDK_WEAK void GXSetVtxDesc(GXAttr attr, GXAttrType type) { SDK_STUB(GXSetVtxDesc); }
SDK_WEAK void GXSetVtxAttrFmt(GXVtxFmt vtxfmt, GXAttr attr, GXCompCnt cnt, GXCompType type, u8 frac) { SDK_STUB(GXSetVtxAttrFmt); }
SDK_WEAK void GXSetTevOrder(GXTevStageID stage, GXTexCoordID coord, GXTexMapID map, GXChannelID color) { SDK_STUB(GXSetTevOrder); }
SDK_WEAK void GXSetChanCtrl(GXChannelID chan, GXBool enable, GXColorSrc amb_src, GXColorSrc mat_src, u32 light_mask, GXDiffuseFn diff_fn, GXAttnFn attn_fn) { SDK_STUB(GXSetChanCtrl); }
SDK_WEAK void GXBegin(GXPrimitive type, GXVtxFmt vtxfmt, u16 nverts) { SDK_STUB(GXBegin); }
SDK_WEAK void GXSetBlendMode(GXBlendMode type, GXBlendFactor src_factor, GXBlendFactor dst_factor, GXLogicOp op) { SDK_STUB(GXSetBlendMode); }
SDK_WEAK void GXLoadPosMtxImm(f32 mtx[3][4], u32 id) { SDK_STUB(GXLoadPosMtxImm); }
SDK_WEAK void GXSetNumTevStages(u8 nStages) { SDK_STUB(GXSetNumTevStages); }
SDK_WEAK void GXClearVtxDesc(void) { SDK_STUB(GXClearVtxDesc); }
SDK_WEAK void GXSetCullMode(GXCullMode mode) { SDK_STUB(GXSetCullMode); }
SDK_WEAK void GXSetNumTexGens(u8 nTexGens) { SDK_STUB(GXSetNumTexGens); }
SDK_WEAK void GXSetTevColorIn(GXTevStageID stage, GXTevColorArg a, GXTevColorArg b, GXTevColorArg c, GXTevColorArg d) { SDK_STUB(GXSetTevColorIn); }
SDK_WEAK void GXSetTevAlphaIn(GXTevStageID stage, GXTevAlphaArg a, GXTevAlphaArg b, GXTevAlphaArg c, GXTevAlphaArg d) { SDK_STUB(GXSetTevAlphaIn); }
SDK_WEAK void GXSetZMode(GXBool compare_enable, GXCompare func, GXBool update_enable) { SDK_STUB(GXSetZMode); }
SDK_WEAK void GXSetTevColorOp(GXTevStageID stage, GXTevOp op, GXTevBias bias, GXTevScale scale, GXBool clamp, GXTevRegID out_reg) { SDK_STUB(GXSetTevColorOp); }
SDK_WEAK void GXSetNumChans(u8 nChans) { SDK_STUB(GXSetNumChans); }
SDK_WEAK void GXSetTevAlphaOp(GXTevStageID stage, GXTevOp op, GXTevBias bias, GXTevScale scale, GXBool clamp, GXTevRegID out_reg) { SDK_STUB(GXSetTevAlphaOp); }
SDK_WEAK void GXSetTexCoordGen2(GXTexCoordID dst_coord, GXTexGenType func, GXTexGenSrc src_param, u32 mtx, GXBool normalize, u32 pt_texmtx) { SDK_STUB(GXSetTexCoordGen2); }
SDK_WEAK void GXSetTevColor(GXTevRegID id, GXColor color) { SDK_STUB(GXSetTevColor); }
SDK_WEAK void GXSetCurrentMtx(u32 id) { SDK_STUB(GXSetCurrentMtx); }
SDK_WEAK void GXSetChanMatColor(GXChannelID chan, GXColor mat_color) { SDK_STUB(GXSetChanMatColor); }
SDK_WEAK void GXSetAlphaUpdate(GXBool update_enable) { SDK_STUB(GXSetAlphaUpdate); }
SDK_WEAK void GXSetColorUpdate(GXBool update_enable) { SDK_STUB(GXSetColorUpdate); }
SDK_WEAK void GXSetAlphaCompare(GXCompare comp0, u8 ref0, GXAlphaOp op, GXCompare comp1, u8 ref1) { SDK_STUB(GXSetAlphaCompare); }
SDK_WEAK void GXSetTevOp(GXTevStageID id, GXTevMode mode) { SDK_STUB(GXSetTevOp); }
SDK_WEAK void GXSetDstAlpha(GXBool enable, u8 alpha) { SDK_STUB(GXSetDstAlpha); }
SDK_WEAK void DCStoreRange(void* addr, u32 nBytes) { SDK_STUB(DCStoreRange); }
SDK_WEAK void GXLoadTexObj(GXTexObj* obj, GXTexMapID id) { SDK_STUB(GXLoadTexObj); }
SDK_WEAK void OSPanic(char* file, int line, char* msg, ...) { SDK_STUB(OSPanic); }
SDK_WEAK BOOL OSRestoreInterrupts(BOOL level) { SDK_STUB(OSRestoreInterrupts); return (BOOL)(level); }
SDK_WEAK int OSSendMessage(struct OSMessageQueue* mq, void* msg, long flags) { SDK_STUB(OSSendMessage); return stub_default<int >(); }
SDK_WEAK int OSReceiveMessage(struct OSMessageQueue* mq, void* msg, long flags) { SDK_STUB(OSReceiveMessage); return stub_default<int >(); }
SDK_WEAK void DCFlushRange(void* addr, u32 nBytes) { SDK_STUB(DCFlushRange); }
SDK_WEAK void GXSetProjection(f32 mtx[4][4], GXProjectionType type) { SDK_STUB(GXSetProjection); }
SDK_WEAK void GXSetZCompLoc(GXBool before_tex) { SDK_STUB(GXSetZCompLoc); }
SDK_WEAK void OSInitMessageQueue(struct OSMessageQueue* mq, void* msgArray, long msgCount) { SDK_STUB(OSInitMessageQueue); }
SDK_WEAK void GXInitTexObj(GXTexObj* obj, void* image_ptr, u16 width, u16 height, GXTexFmt format, GXTexWrapMode wrap_s, GXTexWrapMode wrap_t, u8 mipmap) { SDK_STUB(GXInitTexObj); }
SDK_WEAK void OSUnlockMutex(struct OSMutex* mutex) { SDK_STUB(OSUnlockMutex); }
SDK_WEAK void GXInitTexObjLOD(GXTexObj* obj, GXTexFilter min_filt, GXTexFilter mag_filt, f32 min_lod, f32 max_lod, f32 lod_bias, GXBool bias_clamp, GXBool do_edge_lod, GXAnisotropy max_aniso) { SDK_STUB(GXInitTexObjLOD); }
SDK_WEAK void GXLoadTexMtxImm(f32 mtx[][4], u32 id, GXTexMtxType type) { SDK_STUB(GXLoadTexMtxImm); }
SDK_WEAK s32 DVDReadPrio(DVDFileInfo* fileInfo, void* addr, s32 length, s32 offset, s32 prio) { SDK_STUB(DVDReadPrio); return stub_default<s32 >(); }
SDK_WEAK BOOL OSDisableInterrupts(void) { SDK_STUB(OSDisableInterrupts); return (BOOL)(1); }
SDK_WEAK void GXEnableTexOffsets(GXTexCoordID coord, u8 line_enable, u8 point_enable) { SDK_STUB(GXEnableTexOffsets); }
SDK_WEAK void OSReport(const char*, ...) { SDK_STUB(OSReport); }
SDK_WEAK int OSCreateThread(OSThread* thread, void* (*func)(void*), void* param, void* stack, u32 stackSize, s32 priority, u16 attr) { SDK_STUB(OSCreateThread); return stub_default<int >(); }
SDK_WEAK void OSLockMutex(struct OSMutex* mutex) { SDK_STUB(OSLockMutex); }
SDK_WEAK BOOL DVDClose(DVDFileInfo* fileInfo) { SDK_STUB(DVDClose); return stub_default<BOOL >(); }
SDK_WEAK void GXCallDisplayList(void* list, u32 nbytes) { SDK_STUB(GXCallDisplayList); }
SDK_WEAK void GXSetChanAmbColor(GXChannelID chan, GXColor amb_color) { SDK_STUB(GXSetChanAmbColor); }
SDK_WEAK void VIWaitForRetrace(void) { SDK_STUB(VIWaitForRetrace); }
SDK_WEAK long OSResumeThread(OSThread* thread) { SDK_STUB(OSResumeThread); return stub_default<long >(); }
SDK_WEAK void GXLoadNrmMtxImm(f32 mtx[3][4], u32 id) { SDK_STUB(GXLoadNrmMtxImm); }
SDK_WEAK void GXSetArray(GXAttr attr, const void* base_ptr, u8 stride) { SDK_STUB(GXSetArray); }
SDK_WEAK void GXSetClipMode(GXClipMode mode) { SDK_STUB(GXSetClipMode); }
SDK_WEAK void GXSetTevSwapModeTable(GXTevSwapSel table, GXTevColorChan red, GXTevColorChan green, GXTevColorChan blue, GXTevColorChan alpha) { SDK_STUB(GXSetTevSwapModeTable); }
SDK_WEAK u32 VIGetTvFormat(void) { SDK_STUB(VIGetTvFormat); return stub_default<u32 >(); }
SDK_WEAK OSTick OSGetTick(void) { SDK_STUB(OSGetTick); return stub_default<OSTick >(); }
SDK_WEAK void C_MTXOrtho(Mtx44 m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 f) { SDK_STUB(C_MTXOrtho); }
SDK_WEAK void GXLoadLightObjImm(GXLightObj* lt_obj, GXLightID light) { SDK_STUB(GXLoadLightObjImm); }
SDK_WEAK void GXSetScissor(u32 left, u32 top, u32 wd, u32 ht) { SDK_STUB(GXSetScissor); }
SDK_WEAK void GXSetTevDirect(GXTevStageID tev_stage) { SDK_STUB(GXSetTevDirect); }
SDK_WEAK void GXInitLightColor(GXLightObj* lt_obj, GXColor color) { SDK_STUB(GXInitLightColor); }
SDK_WEAK void GXSetLineWidth(u8 width, GXTexOffset texOffsets) { SDK_STUB(GXSetLineWidth); }
SDK_WEAK void GXSetTevSwapMode(GXTevStageID stage, GXTevSwapSel ras_sel, GXTevSwapSel tex_sel) { SDK_STUB(GXSetTevSwapMode); }
SDK_WEAK void GXSetViewport(f32 left, f32 top, f32 wd, f32 ht, f32 nearz, f32 farz) { SDK_STUB(GXSetViewport); }
SDK_WEAK void C_MTXLookAt(Mtx m, Point3dPtr camPos, VecPtr camUp, Point3dPtr target) { SDK_STUB(C_MTXLookAt); }
SDK_WEAK void DCInvalidateRange(void* addr, u32 nBytes) { SDK_STUB(DCInvalidateRange); }
SDK_WEAK void GXSetIndTexCoordScale(GXIndTexStageID ind_state, GXIndTexScale scale_s, GXIndTexScale scale_t) { SDK_STUB(GXSetIndTexCoordScale); }
SDK_WEAK void GXSetMisc(GXMiscToken token, u32 val) { SDK_STUB(GXSetMisc); }
SDK_WEAK BOOL OSEnableInterrupts(void) { SDK_STUB(OSEnableInterrupts); return (BOOL)(1); }
SDK_WEAK void PSMTXCopy(Mtx src, Mtx dst) { SDK_STUB(PSMTXCopy); }
SDK_WEAK void PSVECNormalize(Vec* vec1, Vec* dst) { SDK_STUB(PSVECNormalize); }
SDK_WEAK void C_MTXPerspective(Mtx44 m, f32 fovY, f32 aspect, f32 n, f32 f) { SDK_STUB(C_MTXPerspective); }
SDK_WEAK void GDSetZMode(unsigned char compare_enable, GXCompare func, unsigned char update_enable) { SDK_STUB(GDSetZMode); }
SDK_WEAK void GXSetNumIndStages(u8 nIndStages) { SDK_STUB(GXSetNumIndStages); }
SDK_WEAK void GXSetTevKColor(GXTevKColorID id, GXColor color) { SDK_STUB(GXSetTevKColor); }
SDK_WEAK void GXSetTexCoordCylWrap(GXTexCoordID coord, u8 s_enable, u8 t_enable) { SDK_STUB(GXSetTexCoordCylWrap); }
SDK_WEAK void GXSetTexCoordScaleManually(GXTexCoordID coord, u8 enable, u16 ss, u16 ts) { SDK_STUB(GXSetTexCoordScaleManually); }
SDK_WEAK OSTime OSGetTime(void) { SDK_STUB(OSGetTime); return stub_default<OSTime >(); }
SDK_WEAK int OSJoinThread(OSThread* thread, void** val) { SDK_STUB(OSJoinThread); return stub_default<int >(); }
SDK_WEAK void PADControlMotor(s32 chan, u32 command) { SDK_STUB(PADControlMotor); }
SDK_WEAK void PSMTXConcat(Mtx mA, Mtx mB, Mtx mAB) { SDK_STUB(PSMTXConcat); }
SDK_WEAK u32 DSPCheckMailToDSP(void) { SDK_STUB(DSPCheckMailToDSP); return stub_default<u32 >(); }
SDK_WEAK BOOL DVDOpen(char* fileName, DVDFileInfo* fileInfo) { SDK_STUB(DVDOpen); return (BOOL)(0); }
SDK_WEAK void GXCopyTex(void* dest, GXBool clear) { SDK_STUB(GXCopyTex); }
SDK_WEAK void GXInitLightPos(GXLightObj* lt_obj, f32 x, f32 y, f32 z) { SDK_STUB(GXInitLightPos); }
SDK_WEAK void GXSetCopyFilter(GXBool aa, const u8 sample_pattern[12][2], GXBool vf, const u8 vfilter[7]) { SDK_STUB(GXSetCopyFilter); }
SDK_WEAK void GXSetTevKColorSel(GXTevStageID stage, GXTevKColorSel sel) { SDK_STUB(GXSetTevKColorSel); }
SDK_WEAK void GXSetTexCopyDst(u16 wd, u16 ht, GXTexFmt fmt, GXBool mipmap) { SDK_STUB(GXSetTexCopyDst); }
SDK_WEAK void GXSetTexCopySrc(u16 left, u16 top, u16 wd, u16 ht) { SDK_STUB(GXSetTexCopySrc); }
SDK_WEAK BOOL OSIsThreadTerminated(OSThread*) { SDK_STUB(OSIsThreadTerminated); return stub_default<BOOL >(); }
SDK_WEAK void PSMTXIdentity(Mtx m) { SDK_STUB(PSMTXIdentity); }
SDK_WEAK u32 VIGetRetraceCount(void) { SDK_STUB(VIGetRetraceCount); return stub_default<u32 >(); }
SDK_WEAK s32 CARDClose(CARDFileInfo* fileInfo) { SDK_STUB(CARDClose); return stub_default<s32 >(); }
SDK_WEAK void DSPSendMailToDSP(u32 mail) { SDK_STUB(DSPSendMailToDSP); }
SDK_WEAK s32 DVDConvertPathToEntrynum(char* pathPtr) { SDK_STUB(DVDConvertPathToEntrynum); return (s32)(-1); }
SDK_WEAK void GXInvalidateTexAll(void) { SDK_STUB(GXInvalidateTexAll); }
SDK_WEAK void GXSetDrawSync(unsigned short token) { SDK_STUB(GXSetDrawSync); }
SDK_WEAK void GXSetTevKAlphaSel(GXTevStageID stage, GXTevKAlphaSel sel) { SDK_STUB(GXSetTevKAlphaSel); }
SDK_WEAK void MTXMultVecSR(Mtx44 m, Vec* src, Vec* dst) { SDK_STUB(MTXMultVecSR); }
SDK_WEAK void OSInitMutex(struct OSMutex* mutex) { SDK_STUB(OSInitMutex); }
SDK_WEAK void OSProtectRange(u32 channel, void* address, u32 nBytes, u32 control) { SDK_STUB(OSProtectRange); }
SDK_WEAK OSErrorHandler OSSetErrorHandler(OSError error, OSErrorHandler handler) { SDK_STUB(OSSetErrorHandler); return stub_default<OSErrorHandler >(); }
SDK_WEAK void OSYieldThread(void) { SDK_STUB(OSYieldThread); }
SDK_WEAK void C_MTXLightPerspective(Mtx m, f32 fovY, f32 aspect, f32 scaleS, f32 scaleT, f32 transS, f32 transT) { SDK_STUB(C_MTXLightPerspective); }
SDK_WEAK void GDSetBlendMode(GXBlendMode type, GXBlendFactor src_factor, GXBlendFactor dst_factor, GXLogicOp logic_op) { SDK_STUB(GDSetBlendMode); }
SDK_WEAK void GXDrawDone(void) { SDK_STUB(GXDrawDone); }
SDK_WEAK void GXPixModeSync(void) { SDK_STUB(GXPixModeSync); }
SDK_WEAK void GXSetIndTexMtx(GXIndTexMtxID mtx_id, f32 offset[2][3], s8 scale_exp) { SDK_STUB(GXSetIndTexMtx); }
SDK_WEAK void GXSetTevColorS10(GXTevRegID id, GXColorS10 color) { SDK_STUB(GXSetTevColorS10); }
SDK_WEAK void OSCancelThread(OSThread*) { SDK_STUB(OSCancelThread); }
SDK_WEAK s32 OSSuspendThread(OSThread* thread) { SDK_STUB(OSSuspendThread); return stub_default<s32 >(); }
SDK_WEAK u32 VIGetNextField(void) { SDK_STUB(VIGetNextField); return (u32)(1); }
SDK_WEAK void VISetBlack(BOOL black) { SDK_STUB(VISetBlack); }
SDK_WEAK void ARQPostRequest(struct ARQRequest* request, u32 owner, u32 type, u32 priority, u32 source, u32 dest, u32 length, ARQCallback callback) { SDK_STUB(ARQPostRequest); }
SDK_WEAK u32 DSPCheckMailFromDSP(void) { SDK_STUB(DSPCheckMailFromDSP); return stub_default<u32 >(); }
SDK_WEAK BOOL DVDChangeDir(char* dirName) { SDK_STUB(DVDChangeDir); return stub_default<BOOL >(); }
SDK_WEAK s32 DVDGetDriveStatus() { SDK_STUB(DVDGetDriveStatus); return stub_default<s32 >(); }
SDK_WEAK void GDFlushCurrToMem(void) { SDK_STUB(GDFlushCurrToMem); }
SDK_WEAK void GDInitGDLObj(GDLObj* dl, void* start, u32 length) { SDK_STUB(GDInitGDLObj); }
SDK_WEAK void GDPadCurr32(void) { SDK_STUB(GDPadCurr32); }
SDK_WEAK void GDSetAlphaCompare(GXCompare comp0, u8 ref0, GXAlphaOp op, GXCompare comp1, u8 ref1) { SDK_STUB(GDSetAlphaCompare); }
SDK_WEAK void GDSetCullMode(GXCullMode mode) { SDK_STUB(GDSetCullMode); }
SDK_WEAK void GDSetDstAlpha(unsigned char enable, unsigned char alpha) { SDK_STUB(GDSetDstAlpha); }
SDK_WEAK u32 GXGetTexBufferSize(u16 width, u16 height, u32 format, u8 mipmap, u8 max_lod) { SDK_STUB(GXGetTexBufferSize); return stub_default<u32 >(); }
SDK_WEAK void GXInitLightAttn(GXLightObj* lt_obj, f32 a0, f32 a1, f32 a2, f32 k0, f32 k1, f32 k2) { SDK_STUB(GXInitLightAttn); }
SDK_WEAK void GXInvalidateVtxCache(void) { SDK_STUB(GXInvalidateVtxCache); }
SDK_WEAK void GXSetCoPlanar(GXBool enable) { SDK_STUB(GXSetCoPlanar); }
SDK_WEAK void GXSetDither(GXBool dither) { SDK_STUB(GXSetDither); }
SDK_WEAK void GXSetIndTexOrder(GXIndTexStageID ind_stage, GXTexCoordID tex_coord, GXTexMapID tex_map) { SDK_STUB(GXSetIndTexOrder); }
SDK_WEAK void GXSetPixelFmt(GXPixelFmt pix_fmt, GXZFmt16 z_fmt) { SDK_STUB(GXSetPixelFmt); }
SDK_WEAK void GXSetPointSize(u8 pointSize, GXTexOffset texOffsets) { SDK_STUB(GXSetPointSize); }
SDK_WEAK OSThread* OSGetCurrentThread(void) { SDK_STUB(OSGetCurrentThread); return stub_default<OSThread* >(); }
SDK_WEAK u32 OSGetProgressiveMode() { SDK_STUB(OSGetProgressiveMode); return stub_default<u32 >(); }
SDK_WEAK void OSSignalCond(struct OSCond* cond) { SDK_STUB(OSSignalCond); }
SDK_WEAK void PSVECCrossProduct(Vec* vec1, Vec* vec2, Vec* dst) { SDK_STUB(PSVECCrossProduct); }
SDK_WEAK void VIFlush(void) { SDK_STUB(VIFlush); }
SDK_WEAK void AISetStreamVolLeft(u8 vol) { SDK_STUB(AISetStreamVolLeft); }
SDK_WEAK void AISetStreamVolRight(u8 vol) { SDK_STUB(AISetStreamVolRight); }
SDK_WEAK u32 ARAlloc(u32 length) { SDK_STUB(ARAlloc); return stub_default<u32 >(); }
SDK_WEAK u32 DSPReadMailFromDSP(void) { SDK_STUB(DSPReadMailFromDSP); return stub_default<u32 >(); }
SDK_WEAK s32 DVDGetCommandBlockStatus(DVDCommandBlock* block) { SDK_STUB(DVDGetCommandBlockStatus); return stub_default<s32 >(); }
SDK_WEAK void GDSetBlendModeEtc(GXBlendMode type, GXBlendFactor src_factor, GXBlendFactor dst_factor, GXLogicOp logic_op, unsigned char color_update_enable, unsigned char alpha_update_enable, unsigned char dither_enable) { SDK_STUB(GDSetBlendModeEtc); }
SDK_WEAK void GXDrawCube(void) { SDK_STUB(GXDrawCube); }
SDK_WEAK void GXInitTexCacheRegion(GXTexRegion* region, u8 is_32b_mipmap, u32 tmem_even, GXTexCacheSize size_even, u32 tmem_odd, GXTexCacheSize size_odd) { SDK_STUB(GXInitTexCacheRegion); }
SDK_WEAK void GXSetTevIndWarp(GXTevStageID tev_stage, GXIndTexStageID ind_stage, u8 signed_offset, u8 replace_mode, GXIndTexMtxID matrix_sel) { SDK_STUB(GXSetTevIndWarp); }
SDK_WEAK void GXSetTevIndirect(GXTevStageID tev_stage, GXIndTexStageID ind_stage, GXIndTexFormat format, GXIndTexBiasSel bias_sel, GXIndTexMtxID matrix_sel, GXIndTexWrap wrap_s, GXIndTexWrap wrap_t, GXBool add_prev, GXBool utc_lod, GXIndTexAlphaSel alpha_sel) { SDK_STUB(GXSetTevIndirect); }
SDK_WEAK OSTime OSCheckStopwatch(OSStopwatch* sw) { SDK_STUB(OSCheckStopwatch); return stub_default<OSTime >(); }
SDK_WEAK void OSSetProgressiveMode(u32 mode) { SDK_STUB(OSSetProgressiveMode); }
SDK_WEAK void OSSetSoundMode(u32 mode) { SDK_STUB(OSSetSoundMode); }
SDK_WEAK void OSStartStopwatch(OSStopwatch* sw) { SDK_STUB(OSStartStopwatch); }
SDK_WEAK void OSStopStopwatch(OSStopwatch* sw) { SDK_STUB(OSStopStopwatch); }
SDK_WEAK void AIInitDMA(u32 start_addr, u32 length) { SDK_STUB(AIInitDMA); }
SDK_WEAK void AISetStreamPlayState(u32 state) { SDK_STUB(AISetStreamPlayState); }
SDK_WEAK s32 CARDGetStatus(s32 chan, s32 fileNo, CARDStat* stat) { SDK_STUB(CARDGetStatus); return stub_default<s32 >(); }
SDK_WEAK BOOL DVDCheckDisk(void) { SDK_STUB(DVDCheckDisk); return stub_default<BOOL >(); }
SDK_WEAK BOOL DVDFastOpen(s32 entrynum, DVDFileInfo* fileInfo) { SDK_STUB(DVDFastOpen); return (BOOL)(0); }
SDK_WEAK BOOL DVDPrepareStreamAsync(DVDFileInfo* fileInfo, u32 length, u32 offset, DVDCallback callback) { SDK_STUB(DVDPrepareStreamAsync); return stub_default<BOOL >(); }
SDK_WEAK BOOL DVDReadAsyncPrio(DVDFileInfo* fileInfo, void* addr, s32 length, s32 offset, DVDCallback callback, s32 prio) { SDK_STUB(DVDReadAsyncPrio); return stub_default<BOOL >(); }
SDK_WEAK BOOL DVDStopStreamAtEndAsync(DVDCommandBlock* block, DVDCBCallback callback) { SDK_STUB(DVDStopStreamAtEndAsync); return stub_default<BOOL >(); }
SDK_WEAK void GDSetChanCtrl(GXChannelID chan, u8 enable, GXColorSrc amb_src, GXColorSrc mat_src, u32 light_mask, GXDiffuseFn diff_fn, GXAttnFn attn_fn) { SDK_STUB(GDSetChanCtrl); }
SDK_WEAK void GDSetGenMode2(u8 nTexGens, u8 nChans, u8 nTevs, u8 nInds, GXCullMode cm) { SDK_STUB(GDSetGenMode2); }
SDK_WEAK void GDSetVtxDescv(const GXVtxDescList* attrPtr) { SDK_STUB(GDSetVtxDescv); }
SDK_WEAK void GXClearPixMetric(void) { SDK_STUB(GXClearPixMetric); }
SDK_WEAK void GXEnableBreakPt(void* break_pt) { SDK_STUB(GXEnableBreakPt); }
SDK_WEAK void GXFlush(void) { SDK_STUB(GXFlush); }
SDK_WEAK void GXGetLightColor(const GXLightObj* lt_obj, GXColor* color) { SDK_STUB(GXGetLightColor); }
SDK_WEAK float GXGetYScaleFactor(u16, u16) { SDK_STUB(GXGetYScaleFactor); return stub_default<float >(); }
SDK_WEAK void GXInitLightAttnA(GXLightObj* lt_obj, f32 a0, f32 a1, f32 a2) { SDK_STUB(GXInitLightAttnA); }
SDK_WEAK void GXInitSpecularDir(GXLightObj* lt_obj, f32 nx, f32 ny, f32 nz) { SDK_STUB(GXInitSpecularDir); }
SDK_WEAK void GXInitTlutObj(GXTlutObj* tlut_obj, void* lut, GXTlutFmt fmt, u16 n_entries) { SDK_STUB(GXInitTlutObj); }
SDK_WEAK void GXSetCopyClamp(GXFBClamp clamp) { SDK_STUB(GXSetCopyClamp); }
SDK_WEAK void GXSetCopyClear(GXColor clear_clr, u32 clear_z) { SDK_STUB(GXSetCopyClear); }
SDK_WEAK void GXSetDispCopyGamma(GXGamma gamma) { SDK_STUB(GXSetDispCopyGamma); }
SDK_WEAK void GXSetFog(GXFogType type, f32 startz, f32 endz, f32 nearz, f32 farz, GXColor color) { SDK_STUB(GXSetFog); }
SDK_WEAK long OSCheckHeap(int heap) { SDK_STUB(OSCheckHeap); return stub_default<long >(); }
SDK_WEAK int OSCreateHeap(void* start, void* end) { SDK_STUB(OSCreateHeap); return stub_default<int >(); }
SDK_WEAK void OSDestroyHeap(int heap) { SDK_STUB(OSDestroyHeap); }
SDK_WEAK void* OSGetArenaHi(void) { SDK_STUB(OSGetArenaHi); return stub_default<void* >(); }
SDK_WEAK u16 OSGetFontEncode(void) { SDK_STUB(OSGetFontEncode); return stub_default<u16 >(); }
SDK_WEAK u32 OSGetSoundMode(void) { SDK_STUB(OSGetSoundMode); return (u32)(1); }
SDK_WEAK int OSJamMessage(struct OSMessageQueue* mq, void* msg, long flags) { SDK_STUB(OSJamMessage); return stub_default<int >(); }
SDK_WEAK BOOL OSTryLockMutex(struct OSMutex* mutex) { SDK_STUB(OSTryLockMutex); return stub_default<BOOL >(); }
SDK_WEAK void PSMTXMultVec(Mtx44 m, Vec* src, Vec* dst) { SDK_STUB(PSMTXMultVec); }
SDK_WEAK void PSMTXTrans(Mtx m, f32 xT, f32 yT, f32 zT) { SDK_STUB(PSMTXTrans); }
SDK_WEAK void VIConfigure(GXRenderModeObj* rm) { SDK_STUB(VIConfigure); }
SDK_WEAK void VISetNextFrameBuffer(void* fb) { SDK_STUB(VISetNextFrameBuffer); }
SDK_WEAK VIRetraceCallback VISetPostRetraceCallback(VIRetraceCallback cb) { SDK_STUB(VISetPostRetraceCallback); return stub_default<VIRetraceCallback >(); }
SDK_WEAK u32 AIGetDSPSampleRate(void) { SDK_STUB(AIGetDSPSampleRate); return (u32)(1); }
SDK_WEAK void AIInit(u8* stack) { SDK_STUB(AIInit); }
SDK_WEAK AIDCallback AIRegisterDMACallback(AIDCallback callback) { SDK_STUB(AIRegisterDMACallback); return stub_default<AIDCallback >(); }
SDK_WEAK void AIResetStreamSampleCount(void) { SDK_STUB(AIResetStreamSampleCount); }
SDK_WEAK void AISetDSPSampleRate(u32 rate) { SDK_STUB(AISetDSPSampleRate); }
SDK_WEAK void AISetStreamSampleRate(u32 rate) { SDK_STUB(AISetStreamSampleRate); }
SDK_WEAK void AIStartDMA(void) { SDK_STUB(AIStartDMA); }
SDK_WEAK u32 ARGetBaseAddress(void) { SDK_STUB(ARGetBaseAddress); return stub_default<u32 >(); }
SDK_WEAK u32 ARGetSize(void) { SDK_STUB(ARGetSize); return (u32)(0x1000000); }
SDK_WEAK u32 ARInit(u32* stack_index_addr, u32 num_entries) { SDK_STUB(ARInit); return stub_default<u32 >(); }
SDK_WEAK void ARQInit(void) { SDK_STUB(ARQInit); }
SDK_WEAK long CARDCheck(long chan) { SDK_STUB(CARDCheck); return (long)(-3); }
SDK_WEAK long CARDCreate(long chan, char* fileName, unsigned long size, struct CARDFileInfo* fileInfo) { SDK_STUB(CARDCreate); return stub_default<long >(); }
SDK_WEAK long CARDFormat(long chan) { SDK_STUB(CARDFormat); return stub_default<long >(); }
SDK_WEAK s32 CARDFreeBlocks(s32 chan, s32* byteNotUsed, s32* filesNotUsed) { SDK_STUB(CARDFreeBlocks); return stub_default<s32 >(); }
SDK_WEAK void CARDInit(void) { SDK_STUB(CARDInit); }
SDK_WEAK s32 CARDMount(s32 chan, void* workArea, CARDCallback detachCallback) { SDK_STUB(CARDMount); return (s32)(-3); }
SDK_WEAK s32 CARDOpen(s32 chan, char* fileName, CARDFileInfo* fileInfo) { SDK_STUB(CARDOpen); return stub_default<s32 >(); }
SDK_WEAK s32 CARDProbeEx(s32 chan, s32* memSize, s32* sectorSize) { SDK_STUB(CARDProbeEx); return (s32)(-3); }
SDK_WEAK long CARDRead(CARDFileInfo* fileInfo, void* buf, s32 length, s32 offset) { SDK_STUB(CARDRead); return stub_default<long >(); }
SDK_WEAK long CARDSetStatus(long chan, long fileNo, struct CARDStat* stat) { SDK_STUB(CARDSetStatus); return stub_default<long >(); }
SDK_WEAK s32 CARDUnmount(s32 chan) { SDK_STUB(CARDUnmount); return stub_default<s32 >(); }
SDK_WEAK long CARDWrite(struct CARDFileInfo* fileInfo, void* buf, long length, long offset) { SDK_STUB(CARDWrite); return stub_default<long >(); }
SDK_WEAK void C_MTXLightFrustum(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 n, f32 scaleS, f32 scaleT, f32 transS, f32 transT) { SDK_STUB(C_MTXLightFrustum); }
SDK_WEAK void C_MTXLightOrtho(Mtx m, f32 t, f32 b, f32 l, f32 r, f32 scaleS, f32 scaleT, f32 transS, f32 transT) { SDK_STUB(C_MTXLightOrtho); }
SDK_WEAK void DBInitComm(int* inputFlagPtr, int* mtrCallback) { SDK_STUB(DBInitComm); }
SDK_WEAK void DCFlushRangeNoSync(void* addr, u32 nBytes) { SDK_STUB(DCFlushRangeNoSync); }
SDK_WEAK void DCZeroRange(void* addr, u32 nBytes) { SDK_STUB(DCZeroRange); }
SDK_WEAK DSPTaskInfo* DSPAddTask(DSPTaskInfo* task) { SDK_STUB(DSPAddTask); return stub_default<DSPTaskInfo* >(); }
SDK_WEAK void DSPAssertInt(void) { SDK_STUB(DSPAssertInt); }
SDK_WEAK void DSPInit(void) { SDK_STUB(DSPInit); }
SDK_WEAK s32 DVDCancel(DVDCommandBlock* block) { SDK_STUB(DVDCancel); return stub_default<s32 >(); }
SDK_WEAK BOOL DVDCancelStreamAsync(DVDCommandBlock* block, DVDCBCallback callback) { SDK_STUB(DVDCancelStreamAsync); return stub_default<BOOL >(); }
SDK_WEAK BOOL DVDCloseDir(DVDDir* dir) { SDK_STUB(DVDCloseDir); return stub_default<BOOL >(); }
SDK_WEAK BOOL DVDGetStreamPlayAddrAsync(DVDCommandBlock* block, DVDCBCallback callback) { SDK_STUB(DVDGetStreamPlayAddrAsync); return stub_default<BOOL >(); }
SDK_WEAK void DVDInit() { SDK_STUB(DVDInit); }
SDK_WEAK BOOL DVDOpenDir(char* dirName, DVDDir* dir) { SDK_STUB(DVDOpenDir); return stub_default<BOOL >(); }
SDK_WEAK BOOL DVDReadDir(DVDDir* dir, DVDDirEntry* dirent) { SDK_STUB(DVDReadDir); return stub_default<BOOL >(); }
SDK_WEAK void GDSetArray(GXAttr attr, void* base_ptr, u8 stride) { SDK_STUB(GDSetArray); }
SDK_WEAK void GDSetArrayRaw(GXAttr attr, u32 base_ptr_raw, u8 stride) { SDK_STUB(GDSetArrayRaw); }
SDK_WEAK void GDSetChanMatColor(GXChannelID chan, GXColor color) { SDK_STUB(GDSetChanMatColor); }
SDK_WEAK void GDSetCurrentMtx(u32 pn, u32 t0, u32 t1, u32 t2, u32 t3, u32 t4, u32 t5, u32 t6, u32 t7) { SDK_STUB(GDSetCurrentMtx); }
SDK_WEAK void GDSetLightAttn(GXLightID light, float a0, float a1, float a2, float k0, float k1, float k2) { SDK_STUB(GDSetLightAttn); }
SDK_WEAK void GDSetLightColor(GXLightID light, GXColor color) { SDK_STUB(GDSetLightColor); }
SDK_WEAK void GDSetLightDir(GXLightID light, float nx, float ny, float nz) { SDK_STUB(GDSetLightDir); }
SDK_WEAK void GDSetLightPos(GXLightID light, float x, float y, float z) { SDK_STUB(GDSetLightPos); }
SDK_WEAK void GDSetOverflowCallback(GDOverflowCb callback) { SDK_STUB(GDSetOverflowCallback); }
SDK_WEAK void GDSetTevOp(GXTevStageID stage, GXTevMode mode) { SDK_STUB(GDSetTevOp); }
SDK_WEAK void GDSetTevOrder(GXTevStageID evenStage, GXTexCoordID coord0, GXTexMapID map0, GXChannelID color0, GXTexCoordID coord1, GXTexMapID map1, GXChannelID color1) { SDK_STUB(GDSetTevOrder); }
SDK_WEAK void GDSetVtxAttrFmtv(GXVtxFmt vtxfmt, const GXVtxAttrFmtList* list) { SDK_STUB(GDSetVtxAttrFmtv); }
SDK_WEAK void GXCopyDisp(void* dest, GXBool clear) { SDK_STUB(GXCopyDisp); }
SDK_WEAK void GXDisableBreakPt(void) { SDK_STUB(GXDisableBreakPt); }
SDK_WEAK void GXDrawSphere(u8 numMajor, u8 numMinor) { SDK_STUB(GXDrawSphere); }
SDK_WEAK GXFifoObj* GXGetCPUFifo(void) { SDK_STUB(GXGetCPUFifo); return stub_default<GXFifoObj* >(); }
SDK_WEAK void GXGetFifoPtrs(GXFifoObj* fifo, void** readPtr, void** writePtr) { SDK_STUB(GXGetFifoPtrs); }
SDK_WEAK u16 GXGetNumXfbLines(u16, float) { SDK_STUB(GXGetNumXfbLines); return stub_default<u16 >(); }
SDK_WEAK void GXGetProjectionv(f32* ptr) { SDK_STUB(GXGetProjectionv); }
SDK_WEAK void GXGetTexObjAll(const GXTexObj* obj, void** image_ptr, u16* width, u16* height, GXTexFmt* format, GXTexWrapMode* wrap_s, GXTexWrapMode* wrap_t, u8* mipmap) { SDK_STUB(GXGetTexObjAll); }
SDK_WEAK u16 GXGetTexObjHeight(const GXTexObj* to) { SDK_STUB(GXGetTexObjHeight); return stub_default<u16 >(); }
SDK_WEAK u16 GXGetTexObjWidth(const GXTexObj* to) { SDK_STUB(GXGetTexObjWidth); return stub_default<u16 >(); }
SDK_WEAK void GXGetViewportv(f32* vp) { SDK_STUB(GXGetViewportv); }
SDK_WEAK GXFifoObj* GXInit(void* base, u32 size) { SDK_STUB(GXInit); return stub_default<GXFifoObj* >(); }
SDK_WEAK void GXInitLightAttnK(GXLightObj* lt_obj, f32 k0, f32 k1, f32 k2) { SDK_STUB(GXInitLightAttnK); }
SDK_WEAK void GXInitLightDistAttn(GXLightObj* lt_obj, f32 ref_dist, f32 ref_br, GXDistAttnFn dist_func) { SDK_STUB(GXInitLightDistAttn); }
SDK_WEAK void GXInitTexObjCI(GXTexObj* obj, void* image_ptr, u16 width, u16 height, GXCITexFmt format, GXTexWrapMode wrap_s, GXTexWrapMode wrap_t, u8 mipmap, u32 tlut_name) { SDK_STUB(GXInitTexObjCI); }
SDK_WEAK void GXLoadNrmMtxIndx3x3(u16 mtx_indx, u32 id) { SDK_STUB(GXLoadNrmMtxIndx3x3); }
SDK_WEAK void GXLoadPosMtxIndx(u16 mtx_indx, u32 id) { SDK_STUB(GXLoadPosMtxIndx); }
SDK_WEAK void GXLoadTlut(GXTlutObj* tlut_obj, u32 tlut_name) { SDK_STUB(GXLoadTlut); }
SDK_WEAK void GXPeekARGB(u16 x, u16 y, u32* color) { SDK_STUB(GXPeekARGB); }
SDK_WEAK void GXPeekZ(u16 x, u16 y, u32* z) { SDK_STUB(GXPeekZ); }
SDK_WEAK void GXPokeAlphaRead(GXAlphaReadMode mode) { SDK_STUB(GXPokeAlphaRead); }
SDK_WEAK void GXProject(f32 x, f32 y, f32 z, f32 mtx[3][4], f32* pm, f32* vp, f32* sx, f32* sy, f32* sz) { SDK_STUB(GXProject); }
SDK_WEAK void GXReadPixMetric(u32* top_pixels_in, u32* top_pixels_out, u32* bot_pixels_in, u32* bot_pixels_out, u32* clr_pixels_in, u32* copy_clks) { SDK_STUB(GXReadPixMetric); }
SDK_WEAK void GXSetDispCopyDst(u16 wd, u16 ht) { SDK_STUB(GXSetDispCopyDst); }
SDK_WEAK void GXSetDispCopyFrame2Field(GXCopyMode mode) { SDK_STUB(GXSetDispCopyFrame2Field); }
SDK_WEAK void GXSetDispCopySrc(u16 left, u16 top, u16 wd, u16 ht) { SDK_STUB(GXSetDispCopySrc); }
SDK_WEAK u32 GXSetDispCopyYScale(f32 vscale) { SDK_STUB(GXSetDispCopyYScale); return stub_default<u32 >(); }
SDK_WEAK void GXSetDrawDone(void) { SDK_STUB(GXSetDrawDone); }
SDK_WEAK GXDrawSyncCallback GXSetDrawSyncCallback(GXDrawSyncCallback cb) { SDK_STUB(GXSetDrawSyncCallback); return stub_default<GXDrawSyncCallback >(); }
SDK_WEAK void GXSetFieldMode(GXBool field_mode, GXBool half_aspect_ratio) { SDK_STUB(GXSetFieldMode); }
SDK_WEAK void GXSetFogRangeAdj(GXBool enable, u16 center, GXFogAdjTable* table) { SDK_STUB(GXSetFogRangeAdj); }
SDK_WEAK void GXSetViewportJitter(f32 left, f32 top, f32 wd, f32 ht, f32 nearz, f32 farz, u32 field) { SDK_STUB(GXSetViewportJitter); }
SDK_WEAK void GXSetVtxAttrFmtv(GXVtxFmt vtxfmt, const GXVtxAttrFmtList* list) { SDK_STUB(GXSetVtxAttrFmtv); }
SDK_WEAK void GXSetZTexture(GXZTexOp op, GXTexFmt fmt, u32 bias) { SDK_STUB(GXSetZTexture); }
SDK_WEAK void GXWaitDrawDone(void) { SDK_STUB(GXWaitDrawDone); }
SDK_WEAK void LCDisable(void) { SDK_STUB(LCDisable); }
SDK_WEAK void LCEnable(void) { SDK_STUB(LCEnable); }
SDK_WEAK void* OSAllocFromHeap(int heap, unsigned long size) { SDK_STUB(OSAllocFromHeap); return stub_default<void* >(); }
SDK_WEAK void OSDetachThread(OSThread* thread) { SDK_STUB(OSDetachThread); }
SDK_WEAK void OSDumpHeap(int heap) { SDK_STUB(OSDumpHeap); }
SDK_WEAK s32 OSEnableScheduler(void) { SDK_STUB(OSEnableScheduler); return stub_default<s32 >(); }
SDK_WEAK void OSExitThread(OSThread* thread) { SDK_STUB(OSExitThread); }
SDK_WEAK void OSFillFPUContext(OSContext* context) { SDK_STUB(OSFillFPUContext); }
SDK_WEAK void OSFreeToHeap(int heap, void* ptr) { SDK_STUB(OSFreeToHeap); }
SDK_WEAK void* OSGetArenaLo(void) { SDK_STUB(OSGetArenaLo); return stub_default<void* >(); }
SDK_WEAK char* OSGetFontTexture(char* string, void** image, s32* x, s32* y, s32* width) { SDK_STUB(OSGetFontTexture); return stub_default<char* >(); }
SDK_WEAK char* OSGetFontWidth(char* string, s32* width) { SDK_STUB(OSGetFontWidth); return stub_default<char* >(); }
SDK_WEAK BOOL OSGetResetSwitchState(void) { SDK_STUB(OSGetResetSwitchState); return stub_default<BOOL >(); }
SDK_WEAK long OSGetThreadPriority(OSThread* thread) { SDK_STUB(OSGetThreadPriority); return stub_default<long >(); }
SDK_WEAK void* OSInitAlloc(void* arenaStart, void* arenaEnd, int maxHeaps) { SDK_STUB(OSInitAlloc); return stub_default<void* >(); }
SDK_WEAK void OSInitCond(struct OSCond* cond) { SDK_STUB(OSInitCond); }
SDK_WEAK BOOL OSInitFont(OSFontHeader* fontData) { SDK_STUB(OSInitFont); return stub_default<BOOL >(); }
SDK_WEAK void OSInitStopwatch(OSStopwatch* sw, char* name) { SDK_STUB(OSInitStopwatch); }
SDK_WEAK void OSInitThreadQueue(OSThreadQueue* queue) { SDK_STUB(OSInitThreadQueue); }
SDK_WEAK unsigned long OSReferentSize(void* ptr) { SDK_STUB(OSReferentSize); return stub_default<unsigned long >(); }
SDK_WEAK void OSResetStopwatch(OSStopwatch* sw) { SDK_STUB(OSResetStopwatch); }
SDK_WEAK void OSResetSystem(int reset, u32 resetCode, BOOL forceMenu) { SDK_STUB(OSResetSystem); }
SDK_WEAK void OSSetArenaHi(void*) { SDK_STUB(OSSetArenaHi); }
SDK_WEAK void OSSetArenaLo(void*) { SDK_STUB(OSSetArenaLo); }
SDK_WEAK void OSSleepThread(OSThreadQueue* queue) { SDK_STUB(OSSleepThread); }
SDK_WEAK void OSTicksToCalendarTime(OSTime ticks, OSCalendarTime* td) { SDK_STUB(OSTicksToCalendarTime); }
SDK_WEAK void OSWaitCond(struct OSCond* cond, struct OSMutex* mutex) { SDK_STUB(OSWaitCond); }
SDK_WEAK void OSWakeupThread(OSThreadQueue* queue) { SDK_STUB(OSWakeupThread); }
SDK_WEAK void PADClamp(PADStatus* status) { SDK_STUB(PADClamp); }
SDK_WEAK BOOL PADInit() { SDK_STUB(PADInit); return (BOOL)(1); }
SDK_WEAK u32 PADRead(struct PADStatus* status) { SDK_STUB(PADRead); return stub_default<u32 >(); }
SDK_WEAK BOOL PADRecalibrate(u32 mask) { SDK_STUB(PADRecalibrate); return (BOOL)(1); }
SDK_WEAK int PADReset(unsigned long mask) { SDK_STUB(PADReset); return (int)(1); }
SDK_WEAK void PADSetAnalogMode(u32 mode) { SDK_STUB(PADSetAnalogMode); }
SDK_WEAK void PADSetSpec(u32 spec) { SDK_STUB(PADSetSpec); }
SDK_WEAK u32 PPCMfmsr() { SDK_STUB(PPCMfmsr); return stub_default<u32 >(); }
SDK_WEAK void PPCSync() { SDK_STUB(PPCSync); }
SDK_WEAK u32 PSMTXInverse(Mtx src, Mtx inv) { SDK_STUB(PSMTXInverse); return stub_default<u32 >(); }
SDK_WEAK void PSMTXRotAxisRad(Mtx m, Vec* axis, f32 rad) { SDK_STUB(PSMTXRotAxisRad); }
SDK_WEAK void PSMTXRotRad(Mtx m, char axis, f32 rad) { SDK_STUB(PSMTXRotRad); }
SDK_WEAK void PSMTXScale(Mtx m, f32 xS, f32 yS, f32 zS) { SDK_STUB(PSMTXScale); }
SDK_WEAK float PSVECMag(Vec* v) { SDK_STUB(PSVECMag); return stub_default<float >(); }
SDK_WEAK f32 PSVECSquareDistance(Vec* vec1, Vec* vec2) { SDK_STUB(PSVECSquareDistance); return stub_default<f32 >(); }
SDK_WEAK u32 THPAudioDecode(s16* audioBuffer, u8* audioFrame, s32 flag) { SDK_STUB(THPAudioDecode); return stub_default<u32 >(); }
SDK_WEAK BOOL THPInit() { SDK_STUB(THPInit); return stub_default<BOOL >(); }
SDK_WEAK s32 THPVideoDecode(void* file, void* tileY, void* tileU, void* tileV, void* work) { SDK_STUB(THPVideoDecode); return stub_default<s32 >(); }
SDK_WEAK u32 VIGetDTVStatus(void) { SDK_STUB(VIGetDTVStatus); return stub_default<u32 >(); }
SDK_WEAK void VIInit(void) { SDK_STUB(VIInit); }
