#!/usr/bin/env python3
"""Generate platform/sdk_stubs.cpp: a weak, logging stub for every Dolphin SDK
function the game/JSystem/THPPlayer call (decomp/docs/progress/port-scope/
api-surface.tsv, plus tools/extra_stubs.txt), with the signature taken from
its declaration in decomp/libs/dolphin/include/dolphin/**. Real implementations elsewhere in
platform/ override the weak stubs at link time. Functions defined inline in
the SDK headers (GD writers, GXVert WG-pipe writers) are skipped."""
import os, re, sys
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)
inc = os.path.join(root, 'decomp', 'libs', 'dolphin', 'include')
tsv = os.path.join(root, 'decomp', 'docs', 'progress', 'port-scope', 'api-surface.tsv')

names = []
for line in open(tsv).read().splitlines()[1:]:
    f = line.split('\t')
    if 'macro-generated' in f[9]:
        continue
    names.append(f[1])
extra = os.path.join(here, 'extra_stubs.txt')
if os.path.exists(extra):
    for l in open(extra):
        l = l.split('#')[0].strip()
        if l and l not in names:
            names.append(l)

# Headers not to pull into the stub TU: __start.h redeclares OSInit/
# OSResetSystem with C++ linkage, DebuggerDriver.h (OdemuExi2 only) clashes
# with DBInterface.h.
SKIP_HEADERS = {'dolphin/__start.h', 'dolphin/odemuexi/DebuggerDriver.h'}
macros = set()
text = {}
for d, _, fs in os.walk(os.path.join(inc, 'dolphin')):
    for f in fs:
        if not f.endswith('.h'):
            continue
        p = os.path.join(d, f)
        s = open(p, encoding='utf-8', errors='replace').read()
        macros.update(re.findall(r'^\s*#\s*define\s+(\w+)\(', s, flags=re.M))
        if os.path.relpath(p, inc) in SKIP_HEADERS:
            continue
        s = re.sub(r'/\*.*?\*/', ' ', s, flags=re.S)
        s = re.sub(r'//[^\n]*', '', s)
        s = re.sub(r'^\s*#(?:[^\n]*\\\n)*[^\n]*', ';', s, flags=re.M)
        text[os.path.relpath(p, inc)] = re.sub(r'\s+', ' ', s)

# Sensible defaults (C++ expressions) where zero is wrong.
DEFAULTS = {
    'OSDisableInterrupts': '1', 'OSEnableInterrupts': '1',
    'OSRestoreInterrupts': 'level', 'PADInit': '1', 'PADRecalibrate': '1',
    'PADReset': '1', 'VIGetNextField': '1', 'OSGetSoundMode': '1',
    'CARDProbeEx': '-3', 'CARDMount': '-3', 'CARDCheck': '-3', 'CARDInit': '0',
    'DVDOpen': '0', 'DVDFastOpen': '0', 'DVDConvertPathToEntrynum': '-1',
    'OSGetConsoleType': '0x10000006', 'AIGetDSPSampleRate': '1',
    'ARGetSize': '0x1000000', 'OSRoundUp32B': '(u32)((x + 31) & ~31u)',
    'OSRoundDown32B': '(u32)(x & ~31u)',
}

out, missing, inline = [], [], []
for n in names:
    if n in macros:
        inline.append(n)
        continue
    pat = re.compile(r'(?:^|[;{}])\s*([A-Za-z_][\w\s\*]*?[\s\*])' + re.escape(n) +
                     r'\s*\(((?:[^()]|\((?:[^()]|\([^()]*\))*\))*)\)\s*([;{])')
    hit = None
    for h, s in sorted(text.items()):
        for m in pat.finditer(s):
            hit = (h, m)
            if m.group(3) == ';':
                break
        if hit and hit[1].group(3) == ';':
            break
    if not hit:
        missing.append(n)
        continue
    h, m = hit
    ret = m.group(1).strip()
    words = ret.split()
    if m.group(3) == '{' or 'inline' in words or 'static' in words:
        inline.append(n)
        continue
    ret = ' '.join(w for w in words if w not in ('extern', '"C"'))
    params = m.group(2).strip()
    # Name unnamed parameters so defaults can refer to x / level.
    if n == 'OSRestoreInterrupts':
        params = 'BOOL level'
    if n in ('OSRoundUp32B', 'OSRoundDown32B'):
        params = 'u32 x'
    body = 'SDK_STUB(%s);' % n
    if ret != 'void':
        d = DEFAULTS.get(n)
        body += (' return (%s)(%s);' % (ret, d)) if d else ' return stub_default<%s >();' % ret
    out.append((h, 'SDK_WEAK %s %s(%s) { %s }' % (ret, n, params, body)))

hdrs = sorted(set(h for h, _ in out))
with open(os.path.join(root, 'platform', 'sdk_stubs.cpp'), 'w') as fp:
    fp.write('// Generated by tools/gen_stubs.py -- do not edit; add real\n'
             '// implementations elsewhere in platform/ (these stubs are weak).\n'
             '#include "port_compat.h"\n#include "port_stub.h"\n')
    for h in hdrs:
        fp.write('#include <%s>\n' % h)
    fp.write('\ntemplate <class T> static inline T stub_default() { T t = T(); return t; }\n\n')
    for h, l in out:
        fp.write(l + '\n')
print('%d stubs, %d inline-in-header skipped, %d not found: %s' % (len(out), len(inline), len(missing), ' '.join(missing)), file=sys.stderr)
print('inline: ' + ' '.join(inline), file=sys.stderr)
