// Generated by tools/mods/shi_layout/offsets.py: where the port keeps the members
// code mods address by retail offset. SMS_OFFSET(Class, retail offset) is a constant;
// a class and offset not in this table does not compile.
#pragma once

struct sms_offset_entry {
    const char *cls;
    unsigned long retail, p32, p64;
};

inline constexpr sms_offset_entry sms_offset_table[] = {
    {"CPolarSubCamera", 0x130, 0x130, 0x15c},  // unk130.Vec
    {"CPolarSubCamera", 0x134, 0x134, 0x160},  // unk130.Vec.y
    {"CPolarSubCamera", 0x138, 0x138, 0x164},  // unk130.Vec.z
    {"CPolarSubCamera", 0x148, 0x148, 0x174},  // unk148.Vec
    {"CPolarSubCamera", 0x14c, 0x14c, 0x178},  // unk148.Vec.y
    {"CPolarSubCamera", 0x150, 0x150, 0x17c},  // unk148.Vec.z
    {"CPolarSubCamera", 0x154, 0x154, 0x180},  // unk154.Vec
    {"CPolarSubCamera", 0x158, 0x158, 0x184},  // unk154.Vec.y
    {"CPolarSubCamera", 0x15c, 0x15c, 0x188},  // unk154.Vec.z
    {"J3DMaterial", 0x28, 0x28, 0x38},  // mTevBlock
    {"JAISound", 0x8, 0xc, 0x10},  // mSoundID
    {"JDrama::TDisplay", 0x42, 0x42, 0x4e},  // unk10.vfilter.[0]
    {"JDrama::TDisplay", 0x43, 0x43, 0x4f},  // unk10.vfilter.[1]
    {"JPABaseEmitter", 0x110, 0x110, 0x1f8},  // unk110
    {"JPABaseEmitter", 0x15c, 0x15c, 0x258},  // mGlobalDynamicsScale.Vec.z
    {"JUTTexture", 0x20, 0x20, 0x20},  // mTexInfo
    {"MActorAnmBck", 0x24, 0x24, 0x38},  // MActorAnmEach<J3DAnmTransformKey>.unk24
    {"MSBgm", 0x14, 0x14, 0x28},  // unk14
    {"MSound", 0x8c, 0x8c, 0xe8},  // JAIBasic.unk8C.[0]
    {"MSound", 0x94, 0x94, 0xf8},  // unk94
    {"MSound", 0x98, 0x98, 0xfc},  // mWaterFirEnabled
    {"MSound", 0x9c, 0x9c, 0x100},  // unk98
    {"MSound", 0xb0, 0xb0, 0x120},  // unkAC.[0]
    {"MSound", 0xbc, 0xbc, 0x138},  // unkAC.[1]
    {"TCameraInbetween", 0x4, 0x4, 0x4},  // mFramesRemaining
    {"TCardSave", 0x1c, 0x1c, 0x28},  // unk1C.[0]
    {"TCardSave", 0x2e9, 0x2e9, 0x471},  // unk2E9
    {"TEnemyMario::TSettingParams", 0x40, 0x40, 0x80},  // mWaterCtMax.TParamT<short>.value
    {"TFlagManager", 0x6c, 0x6c, 0x6c},  // mCardBools.[108]
    {"TFlagManager", 0x6d, 0x6d, 0x6d},  // mCardBools.[109]
    {"TFlagManager", 0x6e, 0x6e, 0x6e},  // mCardBools.[110]
    {"TFlagManager", 0x78, 0x78, 0x78},  // mCardInts.[0]
    {"TFlagManager", 0xd0, 0xd0, 0xd0},  // mGameInts.[0]
    {"TFlagManager", 0xe4, 0xe4, 0xe4},  // mStageBools.[0]
    {"TFlagManager", 0xf4, 0xf4, 0xf4},  // mStageInts.[0]
    {"TFlagManager", 0x11f, 0x11f, 0x11f},  // mStageInts.[10].+3
    {"TFlagManager", 0x1f4, 0x1f4, 0x1f4},  // mStageInts.[64]
    {"TGCConsole2", 0x50, 0x50, 0x54},  // unk50
    {"TGCConsole2", 0x8a, 0x8a, 0x8e},  // unk8A
    {"TGCConsole2", 0x3f4, 0x3f4, 0x600},  // unk3F0
    {"TGCConsole2", 0x574, 0x574, 0x830},  // unk570
    {"TMarDirector", 0x50, 0x50, 0x9c},  // unk50
    {"TMarDirector", 0x68, 0x68, 0xb4},  // unk68
    {"TMarDirector", 0xe4, 0xe4, 0x198},  // unkE4
    {"TMarioEffect", 0x68, 0x68, 0x80},  // unk68
    {"TMarioEffect", 0x7c, 0x7c, 0xa0},  // unk7C
    {"TMarioEffect", 0x80, 0x80, 0xa8},  // unk80
    {"TPathNode", 0x0, 0x0, 0x0},  // unk0
    {"TPathNode", 0x4, 0x4, 0x8},  // unk4.Vec
    {"TPathNode", 0x8, 0x8, 0xc},  // unk4.Vec.y
    {"TPathNode", 0xc, 0xc, 0x10},  // unk4.Vec.z
    {"TPauseMenu2", 0x1c, 0x1c, 0x28},  // mMenuPane
    {"TPauseMenu2", 0xd4, 0xd4, 0x108},  // mStageName
    {"TPauseMenu2", 0x104, 0x104, 0x144},  // mNumItems
    {"TPauseMenu2", 0x118, 0x118, 0x168},  // mCardSave
    {"TSelectMenu", 0x48, 0x48, 0x78},  // mScenarioImg1
    {"TSelectMenu", 0x4c, 0x4c, 0x80},  // mScenarioShadow1
    {"TSelectMenu", 0x70, 0x70, 0xb8},  // mScenarioImg2
    {"TSelectMenu", 0x74, 0x74, 0xc0},  // mScenarioShadow2
    {"TSelectMenu", 0xdc, 0xdc, 0x190},  // mShineMarks.[0]
    {"TSelectMenu", 0xe0, 0xe0, 0x198},  // mShineMarks.[1]
    {"TSelectMenu", 0xe4, 0xe4, 0x1a0},  // mShineMarks.[2]
    {"TSelectMenu", 0xe8, 0xe8, 0x1a8},  // mShineMarks.[3]
    {"TSelectMenu", 0xec, 0xec, 0x1b0},  // mShineMarks.[4]
    {"TSelectMenu", 0x150, 0x150, 0x240},  // mShineUnlockStates.[0]
    {"TSelectShine", 0x24, 0x24, 0x30},  // mSpinning
    {"TSelectShine", 0x48, 0x48, 0x54},  // mAppearing
    {"TSelectShine", 0x49, 0x49, 0x55},  // mDisappearing
    {"TSelectShineManager", 0x10, 0x10, 0x18},  // mShines.[0]
    {"TSelectShineManager", 0x8c, 0x8c, 0xbc},  // mIndex
    {"TSelectShineManager", 0xa7, 0xa7, 0xd7},  // mClosed
    {"TWaterGun", 0x1cec, 0x1cec, 0x38d4},  // unk1CEC
    {"TYoshi", 0x38, 0x38, 0x48},  // mTongue
    {"TYoshi", 0x118, 0x118, 0x160},  // mBodyAnmSound
    {"TYoshi", 0x11c, 0x11c, 0x168},  // mBodyAnmSoundTable
    {"TYoshiTongue", 0x7c, 0x7c, 0xa8},  // mState
};

void sms_offset_not_in_table();  // not constexpr: an unknown entry fails to compile

consteval bool sms_offset_same(const char *a, const char *b) {
    while (*a && *a == *b) ++a, ++b;
    return *a == *b;
}

consteval unsigned long sms_offset_lookup(const char *cls, unsigned long retail) {
    for (const sms_offset_entry &e : sms_offset_table)
        if (e.retail == retail && sms_offset_same(e.cls, cls))
#if __SIZEOF_POINTER__ == 8
            return e.p64;
#else
            return e.p32;
#endif
    sms_offset_not_in_table();
    return 0;
}

#define SMS_OFFSET(cls, off) (sms_offset_lookup(#cls, off))
