#!/usr/bin/env python3
"""Retail offsets inside the game's classes, as the port lays them out.

Code mods address game objects by retail byte offsets (*(u16 *)((u8 *)director + 0x50)).
The port's classes put those members elsewhere: always on 64-bit hosts, and on 32-bit
hosts in classes whose CodeWarrior vtable pointer follows their first members. The mod
sources write SMS_OFFSET(TMarDirector, 0x50) instead (platform/mods/eclipse/mods-port.patch),
which platform/mods/eclipse/shim/sms_offsets.h resolves per host.

  offsets.py query CLASS OFFSET [CLASS OFFSET...]   what is there, and where the port keeps it
  offsets.py header SRC_ROOT... > sms_offsets.h     the table for every SMS_OFFSET the sources use

Inputs, in $SHI_LAYOUT_WORK (see README.md): port32_all.json, port64_all.json (the port's
layouts, exported by export.py from the plain 32- and 64-bit builds) and vlate.json
(vlate.py over the decomp's include/ and libs/*/include/).
"""
import json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import retail

W = os.environ.get('SHI_LAYOUT_WORK', '.')
P = {32: json.load(open(os.path.join(W, 'port32_all.json')))['types'],
     64: json.load(open(os.path.join(W, 'port64_all.json')))['types']}
R32, _ = retail.build(P[32], json.load(open(os.path.join(W, 'vlate.json'))))


def keyed(t):
    out = []; cnt = {}
    for g in t['fields']:
        n = g['name']; k = cnt.get(n, 0); cnt[n] = k + 1
        out.append(((n, k), g))
    return out


def tail_pad(g): return (g['name'] or '').startswith('_pcTailPad')


def locate(T, off, D, TD=None, path=()):
    """(target offset, member path, target member) for retail offset off in port class T"""
    t = R32.get(T); t6 = D.get(TD or T)
    if t is None or t6 is None: return None, path, None
    if off >= t['size']:
        return (t6['size'] if off == t['size'] else None), path + ('<end>',), None
    k6 = dict(keyed(t6))
    for key, g in keyed(t):
        if g['bitsize'] or tail_pad(g): continue
        if g['off'] <= off < g['off'] + g['size']:
            h = k6.get(key)
            if h is None: return None, path + (g['name'],), None
            rel = off - g['off']; p = path + (g['name'],)
            if g['dims']:
                es = g['esize']; idx = rel // es; rel2 = rel - idx * es
                b = h['off'] + idx * h['esize']; p = p + ('[%d]' % idx,)
                if rel2 == 0: return b, p, h
                if 'rec' in g and 'rec' in h:
                    r, p2, m = locate(g['rec'], rel2, D, h['rec'], p)
                    return (None if r is None else b + r), p2, m
                return (b + rel2 if g['esize'] == h['esize'] else None), p + ('+%d' % rel2,), h
            if rel == 0 and not ('rec' in g and not g['base']): return h['off'], p, h
            if 'rec' in g and 'rec' in h:
                r, p2, m = locate(g['rec'], rel, D, h['rec'], p)
                return (None if r is None else h['off'] + r), p2, m
            if rel == 0: return h['off'], p, h
            return (h['off'] + rel if g['size'] == h['size'] else None), p + ('+%d' % rel,), h
    return None, path + ('<padding>',), None


def resolve(cls, off):
    out = {}
    for a in (32, 64):
        o, p, m = locate(cls, off, P[a])
        out[a] = (o, '.'.join(p), m)
    return out


def query(args):
    for i in range(0, len(args), 2):
        cls, off = args[i], int(args[i + 1], 0)
        if cls not in R32:
            print('%s: not a class of the port' % cls); continue
        r = resolve(cls, off)
        print('%s + %#x (retail):' % (cls, off))
        for a in (32, 64):
            o, p, m = r[a]
            what = '%s, %d bytes' % (m['type'], m['size']) if m else '-'
            print('  %d-bit port: %s  %s  (%s)' % (a, '%#x' % o if o is not None else 'NONE', p, what))


USE = re.compile(r'SMS_OFFSET\(\s*([A-Za-z_][\w:<>, ]*?)\s*,\s*(0x[0-9A-Fa-f]+|\d+)\s*\)')


def header(roots):
    uses = set()
    for root in roots:
        for dp, _, fs in os.walk(root):
            if '/.git' in dp: continue
            for f in fs:
                if f.endswith(('.cpp', '.hxx', '.hpp', '.h', '.c')):
                    t = open(os.path.join(dp, f), encoding='utf-8', errors='replace').read()
                    for c, o in USE.findall(t): uses.add((re.sub(r'\s+', ' ', c.strip()), int(o, 0)))
    out = ['// Generated by tools/mods/shi_layout/offsets.py: where the port keeps the members',
           '// code mods address by retail offset. SMS_OFFSET(Class, retail offset) is a constant;',
           '// a class and offset not in this table does not compile.',
           '#pragma once', '',
           'struct sms_offset_entry {', '    const char *cls;', '    unsigned long retail, p32, p64;', '};', '',
           'inline constexpr sms_offset_entry sms_offset_table[] = {']
    bad = []
    for c, o in sorted(uses):
        if c not in R32: bad.append('%s: not a class of the port' % c); continue
        r = resolve(c, o)
        if r[32][0] is None or r[64][0] is None:
            bad.append('%s + %#x: %s / %s' % (c, o, r[32][1], r[64][1])); continue
        out.append('    {"%s", %#x, %#x, %#x},  // %s' % (c, o, r[32][0], r[64][0], r[64][1]))
    out += ['};', '',
            'void sms_offset_not_in_table();  // not constexpr: an unknown entry fails to compile', '',
            'consteval bool sms_offset_same(const char *a, const char *b) {',
            '    while (*a && *a == *b) ++a, ++b;', '    return *a == *b;', '}', '',
            'consteval unsigned long sms_offset_lookup(const char *cls, unsigned long retail) {',
            '    for (const sms_offset_entry &e : sms_offset_table)',
            '        if (e.retail == retail && sms_offset_same(e.cls, cls))',
            '#if __SIZEOF_POINTER__ == 8', '            return e.p64;', '#else', '            return e.p32;', '#endif',
            '    sms_offset_not_in_table();', '    return 0;', '}', '',
            '#define SMS_OFFSET(cls, off) (sms_offset_lookup(#cls, off))']
    print('\n'.join(out))
    for b in bad: print('offsets.py: %s' % b, file=sys.stderr)
    return 1 if bad else 0


if __name__ == '__main__':
    if len(sys.argv) < 3 or sys.argv[1] not in ('query', 'header'): sys.exit(__doc__)
    sys.exit(query(sys.argv[2:]) if sys.argv[1] == 'query' else header(sys.argv[2:]))
